# Generated by Django 6.0.6 on 2026-07-19 11:20

import apps.accounts.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="otpcode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "One-Time Password",
                "verbose_name_plural": "One-Time Passwords",
            },
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", apps.accounts.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="otpcode",
            name="failed_attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Failed Attempts"
            ),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                db_index=True,
                help_text="Enter the user's mobile phone number.",
                max_length=11,
                unique=True,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Postal Code"
            ),
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Six-digit one-time password.",
                max_length=6,
                verbose_name="OTP Code",
            ),
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="expires_at",
            field=models.DateTimeField(verbose_name="Expires At"),
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="is_used",
            field=models.BooleanField(default=False, verbose_name="Used"),
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otp_codes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["user", "code"], name="accounts_ot_user_id_d274d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["expires_at"], name="accounts_ot_expires_2f08f4_idx"
            ),
        ),
    ]
