# Generated by Django 6.0.6 on 2026-07-19 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0002_alter_order_status_alter_orderitem_pack_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(help_text="Amount in IRR (Toman)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INIT", "Initiated"),
                            ("SUCCESS", "Successful"),
                            ("FAIL", "Failed"),
                        ],
                        default="INIT",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        help_text="Authority code from the gateway",
                        max_length=255,
                        null=True,
                        verbose_name="Authority Code",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference ID returned by the gateway",
                        max_length=255,
                        null=True,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cart.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
