# Generated by Django 6.0.6 on 2026-07-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="pack",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="bookvariant",
            name="binding",
            field=models.CharField(
                blank=True, help_text="Hardcover / Paperback", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="bookvariant",
            name="sale_end_date",
            field=models.DateTimeField(
                blank=True, help_text="End of discount period", null=True
            ),
        ),
        migrations.AlterField(
            model_name="bookvariant",
            name="sale_start_date",
            field=models.DateTimeField(
                blank=True, help_text="Start of discount period", null=True
            ),
        ),
        migrations.AlterField(
            model_name="bookvariant",
            name="size",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("pocket", "Pocket"),
                    ("large", "Large"),
                    ("folio", "Folio"),
                    ("mini", "Mini"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
    ]
